%% Voreinstellungen
sgm = 0.5;
prop.pos.X_wish = 0.98;
prop.pos.Y_wish = 0.98;

%% Normalverteilung des Gesamtmoments
axis.fig_m_ges = figure;
axis.ax_m_ges = axes('Parent',axis.fig_m_ges);
dist = [variable_to_test.M_Notw.gesamt_getr];
hold on;
histfit(dist);
title(['Normalverteilung des Gesamtmoments (mit Getriebe i=',num2str(i_Getr),' )']);
grid 'on';
set(axis.ax_m_ges,'XMinorGrid','on');
xlabel('Gesamtmoment aller Motoren [Nm]');
ylabel('Häufigkeit');
distribution.M_ges = fitdist(transpose(dist), 'normal');
temp_1 = [variable_to_test.M_Notw.gesamt_getr];
temp_len = length(unique(i_Moment.permutations(:,3)));
proc(1) = ceil(interp1(temp_1(1:temp_len), i_Moment.permutations(1:temp_len,3), distribution.M_ges.mu + sgm * distribution.M_ges.sigma));
proc(2) = floor(interp1(temp_1(1:temp_len), i_Moment.permutations(1:temp_len,3), distribution.M_ges.mu - sgm * distribution.M_ges.sigma));
text(prop.pos.X_wish * max(xlim), prop.pos.Y_wish * max(ylim), ['\mu = ', num2str(distribution.M_ges.mu), ' Nm', newline, '\sigma = ', num2str(distribution.M_ges.sigma), ' Nm'], ...
    'Background', prop.color.white, ...
    'EdgeColor', prop.color.black, ...
    'HorizontalAlignment','right','VerticalAlignment','top');

axis.drawArrow([distribution.M_ges.mu + sgm * distribution.M_ges.sigma, distribution.M_ges.mu + sgm * distribution.M_ges.sigma], ...
    ylim,'color',prop.color.grey,'ShowArrowHead','off', 'LineStyle','--');
text(distribution.M_ges.mu + sgm * distribution.M_ges.sigma, ...
    prop.pos.Y_wish * max(ylim), [' Achsanteil \approx ', num2str(proc(1)),'% ', newline, ' \leq ', num2str(round(distribution.M_ges.mu + sgm * distribution.M_ges.sigma,2)), ' Nm '], ...
    'FontSize', 10, 'color',prop.color.grey, ...
    'HorizontalAlignment','left','VerticalAlignment','top');

axis.drawArrow([distribution.M_ges.mu - sgm * distribution.M_ges.sigma, distribution.M_ges.mu - sgm * distribution.M_ges.sigma], ...
    ylim,'color',prop.color.grey,'ShowArrowHead','off', 'LineStyle','--');
text(distribution.M_ges.mu - sgm * distribution.M_ges.sigma, ...
    prop.pos.Y_wish * max(ylim), [' Achsanteil \approx ', num2str(proc(2)),'% ', newline, '\geq ', num2str(round(distribution.M_ges.mu - sgm * distribution.M_ges.sigma,2)), ' Nm '], ...
    'FontSize', 10, 'color',prop.color.grey, ...
    'HorizontalAlignment','right','VerticalAlignment','top');
hold off;

%% Normalverteilung der v1-Achse
axis.fig_m_v1 = figure;
axis.ax_m_v1 = axes('Parent',axis.fig_m_v1);
dist = [variable_to_test.M_Notw.pro_Motor_v1_getr];
hold on;
histfit(dist);
title(['Normalverteilung des notw. Moments der v1-Achse (mit Getriebe i=',num2str(i_Getr),' )']);
grid 'on';
set(axis.ax_m_v1,'XMinorGrid','on');
xlabel('Gesamtmoment aller Motoren [Nm]');
ylabel('Häufigkeit');
xlim([0 max([variable_to_test.M_Notw.pro_Motor_h_getr])]);
distribution.v1 = fitdist(transpose(dist), 'normal');
text(prop.pos.X_wish * max(xlim), prop.pos.Y_wish * max(ylim), ['\mu = ', num2str(distribution.v1.mu), ' Nm', newline, '\sigma = ', num2str(distribution.v1.sigma), ' Nm'], ...
    'Background', prop.color.white, ...
    'EdgeColor', prop.color.black, ...
    'HorizontalAlignment','right','VerticalAlignment','top');

axis.drawArrow([distribution.v1.mu + sgm * distribution.v1.sigma, distribution.v1.mu + sgm * distribution.v1.sigma], ...
    ylim,'color',prop.color.grey,'ShowArrowHead','off', 'LineStyle','--');
text(distribution.v1.mu + sgm * distribution.v1.sigma, ...
    prop.pos.Y_wish * max(ylim), [' Achsanteil \approx ', num2str(proc(1)),'% ', newline, ' \leq ', num2str(round(distribution.v1.mu + sgm * distribution.v1.sigma,2)), ' Nm '], ...
    'FontSize', 10, 'color',prop.color.grey, ...
    'HorizontalAlignment','left','VerticalAlignment','top');

axis.drawArrow([distribution.v1.mu - sgm * distribution.v1.sigma, distribution.v1.mu - sgm * distribution.v1.sigma], ...
    ylim,'color',prop.color.grey,'ShowArrowHead','off', 'LineStyle','--');
text(distribution.v1.mu - sgm * distribution.v1.sigma, ...
    prop.pos.Y_wish * max(ylim), [' Achsanteil \approx ', num2str(proc(2)),'% ', newline, '\geq ', num2str(round(distribution.v1.mu - sgm * distribution.v1.sigma,2)), ' Nm '], ...
    'FontSize', 10, 'color',prop.color.grey, ...
    'HorizontalAlignment','right','VerticalAlignment','top');
hold off;

%% Normalverteilung der v2-Achse
axis.fig_m_v2 = figure;
axis.ax_m_v2 = axes('Parent',axis.fig_m_v2);
dist = [variable_to_test.M_Notw.pro_Motor_v2_getr];
hold on;
histfit(dist);
title(['Normalverteilung des notw. Moments der v2-Achse (mit Getriebe i=',num2str(i_Getr),' )']);
grid 'on';
set(axis.ax_m_v2,'XMinorGrid','on');
xlabel('Gesamtmoment aller Motoren [Nm]');
ylabel('Häufigkeit');
xlim([0 max([variable_to_test.M_Notw.pro_Motor_h_getr])]);
distribution.v2 = fitdist(transpose(dist), 'normal');
text(prop.pos.X_wish * max(xlim), prop.pos.Y_wish * max(ylim), ['\mu = ', num2str(distribution.v2.mu), ' Nm', newline, '\sigma = ', num2str(distribution.v2.sigma), ' Nm'], ...
    'Background', prop.color.white, ...
    'EdgeColor', prop.color.black, ...
    'HorizontalAlignment','right','VerticalAlignment','top');

axis.drawArrow([distribution.v2.mu + sgm * distribution.v2.sigma, distribution.v2.mu + sgm * distribution.v2.sigma], ...
    ylim,'color',prop.color.grey,'ShowArrowHead','off', 'LineStyle','--');
text(distribution.v2.mu + sgm * distribution.v2.sigma, ...
    prop.pos.Y_wish * max(ylim), [' Achsanteil \approx ', num2str(proc(1)),'% ', newline, ' \leq ', num2str(round(distribution.v2.mu + sgm * distribution.v2.sigma,2)), ' Nm '], ...
    'FontSize', 10, 'color',prop.color.grey, ...
    'HorizontalAlignment','left','VerticalAlignment','top');

axis.drawArrow([distribution.v2.mu - sgm * distribution.v2.sigma, distribution.v2.mu - sgm * distribution.v2.sigma], ...
    ylim,'color',prop.color.grey,'ShowArrowHead','off', 'LineStyle','--');
text(distribution.v2.mu - sgm * distribution.v2.sigma, ...
    prop.pos.Y_wish * max(ylim), [' Achsanteil \approx ', num2str(proc(2)),'% ', newline, '\geq ', num2str(round(distribution.v2.mu - sgm * distribution.v2.sigma,2)), ' Nm '], ...
    'FontSize', 10, 'color',prop.color.grey, ...
    'HorizontalAlignment','right','VerticalAlignment','top');
hold off;

%% Normalverteilung der h-Achse
axis.fig_m_h = figure;
axis.ax_m_h = axes('Parent',axis.fig_m_h);
dist = [variable_to_test.M_Notw.pro_Motor_h_getr];
hold on;
histfit(dist);
title(['Normalverteilung des notw. Moments der h-Achse (mit Getriebe i=',num2str(i_Getr),' )']);
grid 'on';
set(axis.ax_m_h,'XMinorGrid','on');
xlabel('Gesamtmoment aller Motoren [Nm]');
ylabel('Häufigkeit');
xlim([0 max([variable_to_test.M_Notw.pro_Motor_h_getr])]);
distribution.h = fitdist(transpose(dist), 'normal');
text(prop.pos.X_wish * max(xlim), prop.pos.Y_wish * max(ylim), ['\mu = ', num2str(distribution.h.mu), ' Nm', newline, '\sigma = ', num2str(distribution.h.sigma), ' Nm'], ...
    'Background', prop.color.white, ...
    'EdgeColor', prop.color.black, ...
    'HorizontalAlignment','right','VerticalAlignment','top');

axis.drawArrow([distribution.h.mu + sgm * distribution.h.sigma, distribution.h.mu + sgm * distribution.h.sigma], ...
    ylim,'color',prop.color.grey,'ShowArrowHead','off', 'LineStyle','--');
text(distribution.h.mu + sgm * distribution.h.sigma, ...
    prop.pos.Y_wish * max(ylim), [' Achsanteil \approx ', num2str(proc(1)),'% ', newline, ' \leq ', num2str(round(distribution.h.mu + sgm * distribution.h.sigma,2)), ' Nm '], ...
    'FontSize', 10, 'color',prop.color.grey, ...
    'HorizontalAlignment','left','VerticalAlignment','top');

axis.drawArrow([distribution.h.mu - sgm * distribution.h.sigma, distribution.h.mu - sgm * distribution.h.sigma], ...
    ylim,'color',prop.color.grey,'ShowArrowHead','off', 'LineStyle','--');
text(distribution.h.mu - sgm * distribution.h.sigma, ...
    prop.pos.Y_wish * max(ylim), [' Achsanteil \approx ', num2str(proc(2)),'% ', newline, '\geq ', num2str(round(distribution.h.mu - sgm * distribution.h.sigma,2)), ' Nm '], ...
    'FontSize', 10, 'color',prop.color.grey, ...
    'HorizontalAlignment','right','VerticalAlignment','top');
hold off;
